language: python

python:
    - '2.5'
    - '2.6'
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - 'pypy'

install:
    - 'pip install requests six pep8'

before_script:
    - 'pep8 --ignore=E501,E225 dgis'

script: python setup.py test
